using SourceGenerator.Contracts.Data;

namespace SourceGenerator;

public static class StringConstants
{
    public static string FileHeader { get; } = @$"// <auto-generated>
//     Auto-generated by Ninjadog.SourceGenerator {typeof(DtoGenerator).Assembly.GetName().Version}
// </auto-generated>";
}
