namespace SourceGenerator;

public static class StringConstants
{
    public static string FileHeader { get; } = @$"// <auto-generated>
//     Auto-generated by Ninjadog.SourceGenerator {typeof(DemoGenerator).Assembly.GetName().Version}
// </auto-generated>";
}