using SourceGenerator.Contracts.Data;

namespace SourceGenerator;

public static class StringConstants
{
    public static string FileHeader => @$"// <auto-generated>
//     Auto-generated by Ninjadog.SourceGenerator {typeof(DtoGenerator).Assembly.GetName().Version}
//     {DateTime.Now:R}
// </auto-generated>";

    public static string NullableEnable => @$"

#nullable enable";

    public static string NullableDisable => @$"
#nullable disable";
}
