global using Ninjadog.Engine.Core.Abstractions;
global using Ninjadog.Engine.Core.DomainEvents.Errors;
global using Ninjadog.Engine.Core.DomainEvents.ProcessContent;
global using Ninjadog.Engine.Core.DomainEvents.ProcessTemplate;
global using Ninjadog.Engine.Core.DomainEvents.Run;
global using Ninjadog.Engine.Core.Models;
global using Ninjadog.Settings;
global using Spectre.Console;
global using Spectre.Console.Cli;
global using static Spectre.Console.AnsiConsole;
